apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: guestbook-project
  source:
    repoURL: https://github.com/kobimm1/demo-argo.git
    targetRevision: HEAD
    path: guestbook
    helm:
      releaseName: guestbook
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: guestbook
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true