apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guest
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: /guestbook-service/guest
spec:
  project: dev
  source:
    repoURL: https://github.com/kobimm1/demo-argo.git
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      releaseName: guestBook
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: guestBooks
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true