apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guest
  namespace: argocd
spec:
  project: guest-project
  source:
    repoURL: https://github.com/kobimm1/demo-argo.git
    targetRevision: HEAD
    path: guest
    helm:
      releaseName: guest
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: guest
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true