apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-demo-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kobimm1/applications.git
    targetRevision: HEAD
    path: my-demo-app
    helm:
      releaseName: my_demo_application
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: env0001
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
